### ISSUE TITLE
Aleyesu: Final boss room door doesn't open after defeating Keledros

### ISSUE THREAD

**Issue by Uberzolik** [MSRevive/map-sources#14]
Suposedly it opened in classic. I think it should be fixed regardless, since otherwise players are just trapped inside the room until death/map change.

**Comment by Dridje** [comment]
This has been fixed.  
Upon boss final death, a 10 second relay is triggered that will then open the door.  The time limit is to make sure the door fully closes before getting triggered again.

I fixed the map by doing my own full compile of it.  There is a 2mb difference in map sizes so a thorough playthrough is recommended once the new build is released.
