### ISSUE TITLE
Cleicert Gurukk constantly gets stuck

### ISSUE THREAD

**Issue by CrashWolf** [MSRevive/map-sources#18]
When letting Gurukk take the crystal, he will frequently fail to leave the room and will just keep running back and forth aimlessly. This wouldn't be a problem, except the magic wall in the main area won't open until either he leaves successfully or the player takes the crystal.
Sometimes he will manage to escape the room after a time and the wall will open, but more often than not when this issue occurs the map is just permanently stuck and the player(s) will have to restart.
Suggested fix: open the wall as soon as he takes the crystal instead of waiting for him to leave.

Additionally, either remove the stupid scripted battle between the skeletons and orcs, or let players use healing wave through the wall again, because it takes forever and is just an annoyance.

**Comment by CrashWolf** [comment]
For science we tried killing him, which only made the problem worse, as now he's dead and the door's still not open.

**Comment by Dridje** [comment]
I have uploaded a fixed Cleicert (and with different lighting we can change again after potential feedback).

There is a set of relays to trigger the failure (hard mode) if the orc doesn't walk back in to the darkness.  If he does successfully finish his path then those entities will be killed.

Removed one of the skeletons in the unskippable scene you have to watch on the orcs' introduction.  Should be faster to finish now?
