### ISSUE TITLE
Missing Texture on Nightmare_Thornlands

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/map-sources#29]
Near the map maker's signature area, a texture is missing so the GoldSrc palceholder pink checkerboard is present.

https://steamuserimages-a.akamaihd.net/ugc/5102047032328157350/6FA91F0B1DF2A64984333ACE7D2D2C84759AE22F/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Dridje** [comment]
Looked into this issue.  Yes @SaintWish this is how goldsource does missing textures.  Since we don't have the source I can't fix this problem per se, but I can changed the render amount to 0 (make the brush invisible).  

Marking this as fixed now.
