### ISSUE TITLE
Catacombs Geometry Leak

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/map-sources#30]
Small corner area doesn't seem to have a surface, so it can see through it and into skybox/whatever it may be called for this map. Does that "Hall of mirror" effects that GoldSrc is known for.

https://steamuserimages-a.akamaihd.net/ugc/5102047032333119699/947CF1C4FEC9F1F4DEFE98FCA0C68582EF7E5F97/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Dridje** [comment]
This is an easy fix and has been done, but map requires a bunch more work (lighting and problem brushwork).

Might put this on the backburner until more tickets are cleared up.

**Comment by Dridje** [comment]
This is fixed now.
