### ISSUE TITLE
Secret Shad_Palace Entrance Does Not Work

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/map-sources#31]
Utilizing expended urdual ring in the mscave Shadahar fight does not take the player into the secret area of Shad Palace. Instead, it takes you to the beginning of the map as if it were votemap to normally.

**Comment by Dridje** [comment]
Used RipEnt to rename the mscave transition entity to the same as the secret chamber.  Seems to work now? Will get other people to check when next patch is out.
