### ISSUE TITLE
Nashalrath Final Boos Room Skybox Issue

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/map-sources#33]
See screenshot. Looks like a water part of the map is bleeding through the skybox during the Jaminporlantz fight:

https://steamuserimages-a.akamaihd.net/ugc/2036223035867637585/67259BF6ABC69BFA28823BF9A4B7843D642537DB/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by frendship-loost** [comment]
Unfortunately that is normal for goldsource engine. For some reason, certain worldents visibility, usually water, leaks through sky brushes. I assume that particular water plane is from the reality tear section? The only thing to be done is to perhaps move the boss arena to the upper-area of the map grid, above any water planes.

**Comment by SaintWish** [comment]
> Unfortunately that is normal for goldsource engine. For some reason, certain worldents visibility, usually water, leaks through sky brushes. I assume that particular water plane is from the reality tear section? The only thing to be done is to perhaps move the boss arena to the upper-area of the map grid, above any water planes.
> 
> Would need testing, but I believe it is related to sky brushes (or null textured boxes) leaking through each other. In other words, if that water plane were encased by a solid-textured world brush box, it may not leak.

I wonder if such a thing would still occur with a new renderer?

**Comment by Dridje** [comment]
I did take a look at the map file, it does look quite crammed so if the new renderer doesn't work out, I'll take a look then.  Putting low priority tag for now.  

This same issue happens on m2_quest as well (and we don't have a source to fix it).

**Comment by Dridje** [comment]
Very close to being finished with this fix!  :D :D :D

**Comment by Dridje** [comment]
So just looking @ the github issues.... this was fixed and map has been modified slightly.  new spiffy 3d skybox from @frendship-loost.  Marking closed
