### ISSUE TITLE
Helena draw distance is low.

### ISSUE THREAD

**Issue by AldenDwyer** [MSRevive/map-sources#36]
![helena1](https://user-images.githubusercontent.com/125112622/218242239-915d5ae5-e625-415f-88d4-00ba5c637b46.png)
![helena2](https://user-images.githubusercontent.com/125112622/218242242-baf7d75a-bc95-4553-ad8c-15a53deba4b3.png)

Helena's draw distance is short enough that it clips the mountains from view from the town.

**Comment by Dridje** [comment]
Increased max distance from 5k to 7.5k units, seemed to be enough when I ran through it.
