### ISSUE TITLE
Uptown Deralia gate lamps in are floating

### ISSUE THREAD

**Issue by Furion001** [MSRevive/map-sources#39]
![newderalia lamp gap](https://user-images.githubusercontent.com/7419121/218874879-4bed7533-3c25-4d79-ac8c-c104c342e3bd.jpg)
 Picture should provide enough details.

**Comment by Furion001** [comment]
![20230214153153_1](https://user-images.githubusercontent.com/7419121/218878253-32552d94-fb32-469c-9fcb-341e53c2e49f.jpg)
Addendum: Sidewalk is weird.

**Comment by Dridje** [comment]
Will look into fixing this issues later this week.

**Comment by Dridje** [comment]
Done
