### ISSUE TITLE
Fallen Knight in basement of Chapel does not awake

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/map-sources#42]
When entering the basement, the fallen knight does not stand up to engage the player.

https://steamuserimages-a.akamaihd.net/ugc/2005827551382948724/B8F496B094E814FCEE4BEC9F6AEAE9F1BC3BFA01/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Dridje** [comment]
He'll automatically get up after 3 seconds to whoop your ass if  you don't approach him.
