### ISSUE TITLE
Old_helena: Map crashes after touching trigger for serrold to walk up, & talk to the player.

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#5]
Crashes after it gets a little bit into his speech. Not a script-side issue, I believe it's map side.

**Comment by greatguys1** [comment]
It might be related to this: https://github.com/MSRevive/MasterSwordRebirth/commit/e57b197f1a665f304d25ad906b42d48d2e6aa31a

**Comment by SaintWish** [comment]
Fixed by this commit https://github.com/MSRevive/MasterSwordRebirth/commit/c7bb6546581a1674dda8633f04a0864210a62c15
