### ISSUE TITLE
Bloodshrine spinning platforms are irritating, and should be replaced

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#55]
The spinning platforms in bloodshrine are the biggest cause of frustration in that map. Enemies are too hard to reach, and players are forced to use their hard earned ammo to slowly clear the room to be able to jump across. This is a huge burden on the pace of the map, and the spinning platforms should be replaced with something else.

**Comment by Dridje** [comment]
I can do a temporary fix of slowing the rotation down.  Will update tomorrow.

**Comment by Dridje** [comment]
Tomorrow = 5 days good to know.  

I have slowed down all the platforms movement and rotation.  All are the exact same speed/rotations too.
