### ISSUE TITLE
Isle monster name issues

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#59]
"One orc is named "fororc1" for some reason"
https://steamuserimages-a.akamaihd.net/ugc/2017094058207166982/B65492861F3BF82C38215CB74C9BF8B125E0372E/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

"Orc in the goblin tunnel is called a "Beseker" instead of a "Berserker""
https://steamuserimages-a.akamaihd.net/ugc/2017094058207166858/A650E46C8F4044B4E5F5F085B89512FC5E8A9582/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Dridje** [comment]
Quick ripEnt job to fix these.
