### ISSUE TITLE
Improve lodagond-4 "protect the crystal" encounter

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#6]
Currently, guarding the crystal isn't very fun. The player could do a lot of things right and still lose.

Potential fixes:
- The bludgeons could be removed from the yellow crystal area to more skeletons or something more manageable
- The crystal death spawns a new encounter instead of map reset

**Comment by SaintWish** [comment]
Improved with Dridje's edit of lodagond-4 that puts the yellow crystal behind a wall that reveals it self after it is completed. https://github.com/MSRevive/map-sources/commit/941810357028a7711bf3d5bb70a4241ecc14e117
