### ISSUE TITLE
hemlock map broken

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#60]
"as title states, fosrer and I were running it and Im not sure if its final room but the arena fight seems to be broken, killed everyone and nothing happened"
![image](https://github.com/MSRevive/map-sources/assets/24220703/254e7e2b-b335-488b-ad17-4969d5ab6e8d)

**Comment by Dridje** [comment]
Played through the map solo and everything worked correctly.  Were you using the gutbuster by any chance?  Wondering if maybe that messed up a kill trigger?

**Comment by Dridje** [comment]
Closing this ticket as no further information given and map ran correctly for me.
