### ISSUE TITLE
Thornlands 'The Rock' Johnson

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/map-sources#61]
![image](https://github.com/MSRevive/map-sources/assets/85242183/c07dd1fa-1aa6-4f7c-abff-650fe35f2117)

'The Rock' of Thornlands has this new texture on its rocky surface. It's grass blended to rock, and so the detail texture is set to something resembling grass. This causes the rock to look weird, can the detail texture be changed for this specific texture?

**Comment by Dridje** [comment]
GOT EM

That isn't actually a rock but a beige grass!

...will modify the detailtexture tomorrow.

**Comment by Dridje** [comment]
Now uses a stone detailtexture.  Closing now.
