### ISSUE TITLE
Merge shad desert series update.

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/map-sources#63]
[shad_palace_recomp03082024.zip](https://github.com/MSRevive/map-sources/files/14544999/shad_palace_recomp03082024.zip)
I updated shad palace to have improved lighting, a 3D model-based skybox, and fixed a few map issues to optimize engine limits. The version currently out on the developer branch is out of date.

**Comment by frendship-loost** [comment]
I have all of the Rickler desert series updated in the same fashion just let me know in this ticket if I should provide them all.

**Comment by frendship-loost** [comment]
[sorc_villa_recomp01312024.zip](https://github.com/MSRevive/map-sources/files/14545004/sorc_villa_recomp01312024.zip)
sorc_villa improved lighting, added 3D model-based skybox accurate to lighting.

**Comment by frendship-loost** [comment]
[aleyesu_recomp01302024.zip](https://github.com/MSRevive/map-sources/files/14545009/aleyesu_recomp01302024.zip)
Aleyesu improved lighting, added 3D model-based skybox accurate to lighting.

**Comment by frendship-loost** [comment]
[aluhandra2_recomp01302024.zip](https://github.com/MSRevive/map-sources/files/14545011/aluhandra2_recomp01302024.zip)
Aluhandra2 improved lighting, fixed some brush errors and VIS problems, added 3D model-based skybox accurate to lighting.

**Comment by frendship-loost** [comment]
All of these zips have a duplicated terrain model across them all, shad_palace has an additional special model to give it more detail.

**Comment by greatguys1** [comment]
We need the map sources here too, can you provide them?

**Comment by greatguys1** [comment]
All merged.
