### ISSUE TITLE
New Cleicert breakable didn't trigger.

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/map-sources#7]
![image](https://user-images.githubusercontent.com/85242183/194739711-462ac53b-8f1b-4ea2-ad56-fa9171e68754.png)

This breakable thing didn't trigger when it should have, happened one time so far.

**Comment by SaintWish** [comment]
Weird, we had that problem before if I remember right, but thought we fixed it. Cheers for letting us know.

**Comment by frendship-loost** [comment]
Twice in a row, seems to be reliable.

**Comment by Dridje** [comment]
I'd recommend looking at the ms_npcscript entity.  It doesn't look like the orc or the skeleton were working properly.  I think it may be an issue with the 'animation' aspect of it.

**Comment by Dridje** [comment]
Okay, I've done testing on the ms_npcscript entity on a new map.
'Move' and 'Play Anim' work on their own but if you select 'Move, then Play Anim' (type 3), you only get the movement.  This is what is breaking the Returning to Stone skeleton, Gurukk the Heavy (crystal pictured above) and likely the orc destroying the crystal at the end of map.

**Comment by Dridje** [comment]
Ran through the map tonight (with devcmd slayall) and tested all the ms_npcscript encounters.  The issue seems to be fixed for all of the listed above so map is working as intended again.
