### ISSUE TITLE
Test what happens if ms_player_spec is missing

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/map-sources#8]
We should further test what happens if a map is missing the ``ms_player_spec`` entity. 
As J-M pointed out:
> This is a great suggestion. I'm guessing the most likely reason some maps don't have this entity is that some mappers didn't really know what ms_player_spec is used for. Also: if an ms_player_spec is missing, the mod will place the camera (of the player character selection screen) at 0,0,0 and this might lead to the hall-of-mirrors effect, if 0,0,0 is (partially) outside the playable area of the map

**Comment by Dridje** [comment]
I just experimented with this to confirm.  It looks like the lack of a ms_player_spec will put the view into a ms_player_spawn entity.

**Comment by SaintWish** [comment]
That's good then, cheers for confirming.
